export interface admission{
    studentID?:number ,
    studentName: string,
    dateOfBirth: string,
    gender: string,
    bloodGroup:string,
    fathersName: string,
    mothersName:string ,
    fatherOccupation:string ,
    motherOccupation:string ,
    familyIncome:number,
    mobile: string,
    email:string,
    state: string,
    stateName?:string,
    district:string,
    districtName:string,
    pincode: string,
    address: string,
    imagePath: string,
    class: string,
    className?:string,
    sectionId:number ,
    sectionName?:string,
    password?: string,
    enrollmentDate?:string
}